### ISSUE TITLE
关于如何让 spark wechat 新建 container 的时候时不丢失记录

### ISSUE THREAD

**Issue by floating-cat** [276562578/easy_install#1]
您好，

> https://github.com/276562578/easy_install/blob/main/doc/wechat/linux.md
PS 原安装程序会默认删除应用的缓存，我不想每次新建container的时候丢失记录，所以进行了一点魔改，如果因此出现问题请告知我

我看您在这篇文章里提到您进行了一些魔改，现在每次新建 container 的时候不会丢失记录了？
可以请您说明一下你是具体怎么魔改的吗？
我也在搭建一个基于 spark 的 wechat docker 版本，所以好奇你是怎么实现的。是修改了某个 sh 文件吗？
谢谢了。

**Comment by 276562578** [comment]
`sed -i 's/rm -rf "$WINEPREFIX"/sleep 1/g' /opt/deepinwine/tools/spark_run_v4.sh`
即可

**Comment by 276562578** [comment]
我之后可能会把Dockerfile分享出来，如果可以你也可以分享出来一起优化

**Comment by floating-cat** [comment]
@276562578 感谢！我的 Dockerfile 在这里：https://github.com/floating-cat/wechat-in-docker/blob/main/Dockerfile
欢迎参考。我也从你的那篇文章里参考和学习了很多。
另外我的主项目下还有一个 run.sh 来修复了切换到其他程序时，会有一个透明的阴影窗口残留的问题。
